[functions]
directory = "netlify/functions"

[[redirects]]
from = "/airport/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/waypoint/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/navaid/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/thank-you"
to = "/index.html"
status = 200
